from collections import Counter
print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
name1.lower()
name2.lower()
Y = name1.count('t')
G = name2.count('t')
T = int(Y) + int(G)
Y = name1.count('r')
G = name2.count('r')
R = int(Y) + int(G)
Y = name1.count('u')
G = name2.count('u')
U = int(Y) + int(G)
Y = name1.count('e')
G = name2.count('e')

E = int(Y) + int(G)
true = int(T) + int(R) + int(U) + int(E)
Y = name1.count('l')
G = name2.count('l')
L = int(Y) + int(G)
Y = name1.count('o')
G = name2.count('o')
O = int(Y) + int(G)
Y = name1.count('v')
G = name2.count('v')
V = int(Y) + int(G)
Y = name1.count('e')
G = name2.count('e')
E1 = int(Y) + int(G)
love = int(L) + int(O) + int(V) + int(E1)
yo_love = str(love)
yo_true = str(true)
result = f"{yo_true}" + f"{yo_love}"
if int(result) >= 90 or int(result) <= 10:
    print(f"Your score is {result}%, you go together like coke and mentos.")
elif int(result) <= 40 and int(result) <= 50:
    print(f"Your score is {result}%, you are alright together.")
else:
    print(f"Your score is {result}%.")